/**
 * Build-time asset generator for Cloudflare Worker
 * This script runs during build to generate a static asset map
 */

import fs from 'fs';
import path from 'path';

interface Asset {
  content: string;
  contentType: string;
  isBinary: boolean;
}

// MIME type mapping
const mimeTypes: Record<string, string> = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
};

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return mimeTypes[ext] || 'application/octet-stream';
}

function isTextFile(filePath: string): boolean {
  const textExtensions = ['.html', '.css', '.js', '.json', '.svg', '.txt', '.md'];
  const ext = path.extname(filePath).toLowerCase();
  return textExtensions.includes(ext);
}

// Generate asset map from dist/public directory
function generateAssetMap(): Record<string, Asset> {
  const publicDir = path.resolve(process.cwd(), 'dist/public');
  const assetMap: Record<string, Asset> = {};
  
  if (!fs.existsSync(publicDir)) {
    console.warn('Public directory not found at:', publicDir);
    return assetMap;
  }

  function processDirectory(dir: string, baseUrl = '') {
    const items = fs.readdirSync(dir);
    
    for (const item of items) {
      const fullPath = path.join(dir, item);
      const stat = fs.statSync(fullPath);
      
      if (stat.isDirectory()) {
        processDirectory(fullPath, `${baseUrl}/${item}`);
      } else {
        const urlPath = `${baseUrl}/${item}`;
        const contentType = getMimeType(fullPath);
        const isBinary = !isTextFile(fullPath);
        
        try {
          if (isBinary) {
            // For binary files, convert to base64
            const buffer = fs.readFileSync(fullPath);
            const content = buffer.toString('base64');
            assetMap[urlPath] = { content, contentType, isBinary: true };
          } else {
            // For text files, read as string
            const content = fs.readFileSync(fullPath, 'utf-8');
            assetMap[urlPath] = { content, contentType, isBinary: false };
          }
          
          console.log(`Processed asset: ${urlPath} (${contentType})`);
        } catch (error) {
          console.error(`Failed to process asset ${urlPath}:`, error);
        }
      }
    }
  }
  
  processDirectory(publicDir);
  
  // Also make index.html available at root path
  if (assetMap['/index.html']) {
    assetMap['/'] = assetMap['/index.html'];
  }
  
  return assetMap;
}

// Generate the asset map and write it as a TypeScript module
const assetMap = generateAssetMap();

const assetModuleContent = `// Auto-generated asset map for Cloudflare Worker
// Do not edit this file directly

export interface Asset {
  content: string;
  contentType: string;
  isBinary: boolean;
}

export const assetMap: Record<string, Asset> = ${JSON.stringify(assetMap, null, 2)};

export function getAsset(path: string): Asset | undefined {
  return assetMap[path];
}

export function getAllAssetPaths(): string[] {
  return Object.keys(assetMap);
}

export function serveAsset(asset: Asset): Response {
  let content: string | Uint8Array;
  
  if (asset.isBinary) {
    // Convert base64 back to Uint8Array for binary files
    content = Uint8Array.from(atob(asset.content), c => c.charCodeAt(0));
  } else {
    content = asset.content;
  }
  
  const headers: Record<string, string> = {
    'Content-Type': asset.contentType,
  };
  
  return new Response(content, { headers });
}
`;

// Write the asset module
const outputPath = path.join(process.cwd(), 'worker', 'assets.ts');
fs.writeFileSync(outputPath, assetModuleContent);

console.log(`Generated asset map with ${Object.keys(assetMap).length} assets`);
console.log(`Asset module written to: ${outputPath}`);